### PR TITLE
feat!: support Keycloak as identity provider

### PR DESCRIPTION
**Pull request by nicklas-delphai**
- config now uses absolute path for `dotenv` 
- `access_token` verified with keycloak public key
- `mongo_user_id` and `mongo_client_id` provided to metadata stays the same for backwards compatibility

### CODE REVIEW

**Review by amaslyaev — COMMENTED** [review]
async-gateway is a Barath's branch. I do not have full understanding how it works yet, so cannot assess changes.
Maybe only one point. As I can see, 'Authorization' header is always required. I think, that is right, but applying this change will require the immediate change in every repo that use gRPC calls.

**Comment by nicklas-delphai** [comment]
> async-gateway is a Barath's branch. I do not have full understanding how it works yet, so cannot assess changes.
> Maybe only one point. As I can see, 'Authorization' header is always required. I think, that is right, but applying this change will require the immediate change in every repo that use gRPC calls.

Yeah I though that this might be a breaking change, but I'm not sure what you mean with "every repo that uses gRPC calls". This is only gateway, which is secured this way. I believe (haven't looked in the code) gRPC calls not go to gateway but rather over HTTP2.0 directly to the service. Please correct me if I'm mistaken.

**Comment by amaslyaev** [comment]
> > async-gateway is a Barath's branch. I do not have full understanding how it works yet, so cannot assess changes.
> > Maybe only one point. As I can see, 'Authorization' header is always required. I think, that is right, but applying this change will require the immediate change in every repo that use gRPC calls.
> 
> Yeah I though that this might be a breaking change, but I'm not sure what you mean with "every repo that uses gRPC calls". This is only gateway, which is secured this way. I believe (haven't looked in the code) gRPC calls not go to gateway but rather over HTTP2.0 directly to the service. Please correct me if I'm mistaken.

Yes, but anyway we have to be careful. Anyway, it will be not a trivial task to merge delphai-utils into delphai-backend-utils, so now we can merge this PR

**Review by amaslyaev — APPROVED** [review]

**Comment by nicklas-delphai** [comment]
@amaslyaev I made another commit today fetching keycloak public keys in intervals to allow for rotating keys.

**Pull request merged**
